# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [src, main.py]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
humans: # Replace with a single Humans username: Egamberdiyev Sardor card-donate: 4455 5500 1968 9963
otechie: # Replace with a single Otechie (https://otechie.com/savip)
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['humans-card: 4455 5500 1968 9963', 'https://otechie.com/savip']
